# Generated by Django 5.1.6 on 2025-02-18 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=200)),
                ('prenom', models.CharField(max_length=200)),
                ('profession', models.CharField(max_length=200)),
                ('secteur', models.CharField(max_length=200)),
            ],
        ),
    ]
